apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
#  argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/extra_config
            name: my-cm
            readOnly: true
      volumes:
        - name: my-cm
          configMap:
            name: my-cm      
