apiVersion: apps/v1
kind: Deployment
metadata:
  name: long-init
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  # argocd.argoproj.io/sync-options: ServerSideApply=true    
spec:
  selector:
    matchLabels:
      app: long-init
  template:
    metadata:
      labels:
        app: long-init
    spec:
      containers:
      - name: long-init-done
        image: busybox
        command:
        - /bin/sh
        - -c
        - 'while true ; do sleep 15 && echo still here ; done'
      initContainers:
      - name: init
        image: busybox
        command:
        - /bin/sh
        - -c
        - 'sleep 15 && echo wake up'