apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: waves-ssa-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io    
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: default
  source:
    repoURL: https://github.com/hau21um/waves-ssa-demo.git
    path: waves-ssa-demo
    targetRevision: waves
    directory:
      recurse: false
      include: '*.yaml'
  destination:
      server: https://kubernetes.default.svc
      namespace: waves-ssa-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true 
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground 
    - PruneLast=true 
